openapi: 3.0.0
info:
  version: 1.0.0
  title: Recipe Service
  description: API for managing and retrieving recipes

paths:
  /recipes:
    get:
      summary: Get a list of recipes
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: Vegan Pasta
                  tags:
                    - vegan
                    - gluten-free
                  timeToMake: 30 minutes
                - id: 2
                  name: Healthy Salad
                  tags:
                    - vegetarian
                    - low-calorie
                  timeToMake: 15 minutes

  /recipes/{recipeId}:
    get:
      summary: Get details of a specific recipe
      parameters:
        - name: recipeId
          in: path
          required: true
          description: ID of the recipe
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: Vegan Pasta
                tags:
                  - vegan
                  - gluten-free
                timeToMake: 30 minutes
                servings: 4
                ingredients:
                  - name: Pasta
                    amount: 250
                    measurement: grams
                  - name: Tomato Sauce
                    amount: 1
                    measurement: cup
                  - name: Vegetables
                    amount: 1
                    measurement: cup
